gestione/urls.py
from django.conf.urls import url
from . import views
from . import aiace

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="indice"),
    
    url(r'^magazzino/$', views.MagazzinoView.as_view(), name="magazzino"),
    url(r'^creaprodotto/$', views.CreaProdottoView.as_view(), name="creaprodotto"),
    url(r'^prodotto/(?P<pk>[0-9]+)$', views.ProdottoView.as_view(), name="prodotto"),
    
    url(r'^categorie/$', views.CategorieView.as_view(), name="categorie"),
    url(r'^creacategoria/$', views.CreaCategoriaView.as_view(), name="creacategoria"),
    url(r'^categoria/(?P<pk>[0-9]+)$', views.CategoriaView.as_view(), name="categoria"),
    
    url(r'^tipoanagrafiche/$', views.TipoAnagraficheView.as_view(), name="tipoanagrafiche"),
    url(r'^creatipoanagrafica/$', views.CreaTipoAnagraficaView.as_view(), name="creatipoanagrafica"),
    url(r'^tipoanagrafica/(?P<pk>[0-9]+)$', views.TipoAnagraficaView.as_view(), name="tipoanagrafica"),
    
    url(r'^anagrafiche/$', views.AnagraficheView.as_view(), name="anagrafiche"),
    url(r'^creaanagrafica/$', views.CreaAnagraficaView.as_view(), name="creaanagrafica"),
    url(r'^anagrafica/(?P<pk>[0-9]+)$', views.AnagraficaView.as_view(), name="anagrafica"),
    
    url(r'^ricarichi/$', views.RicarichiView.as_view(), name="ricarichi"),
    url(r'^crearicarico/$', views.CreaRicaricoView.as_view(), name="crearicarico"),
    url(r'^ricarico/(?P<pk>[0-9]+)$', views.RicaricoView.as_view(), name="ricarico"),
    
    url(r'^listaiva/$', views.ListaIVAView.as_view(), name="listaiva"),
    url(r'^creaiva/$', views.CreaIVAView.as_view(), name="creaiva"),
    url(r'^iva/(?P<pk>[0-9]+)$', views.IVAView.as_view(), name="iva"),
    
    url(r'^carichi/$', views.CarichiView.as_view(), name="carichi"),
    url(r'^creacarico/$', views.CreaCaricoView.as_view(), name="creacarico"),
    url(r'^creacaricodyn/$', views.CreaCaricoDynView.as_view(), name="creacaricodyn"),
    url(r'^caricaprodotti/$', views.caricaProdotti, name="caricaprodotti"),
    
    url(r'^carico/(?P<pk>[0-9]+)$', views.CaricoView.as_view(), name="carico"),
    url(r'^dettagliocarico/(?P<pk>[0-9]+)$', views.DettaglioCaricoView.as_view(), name="dettagliocarico"),
    
    url(r'^vocicarico/$', views.VociCaricoView.as_view(), name="vocicarico"),
    url(r'^creavocecarico/$', views.CreaVoceCaricoView.as_view(), name="creavocecarico"),
    url(r'^vocecarico/(?P<pk>[0-9]+)$', views.VoceCaricoView.as_view(), name="vocecarico"),
    
    url(r'^scarichi/$', views.ScarichiView.as_view(), name="scarichi"),
    url(r'^creascarico/$', views.CreaScaricoView.as_view(), name="creascarico"),
    url(r'^creascaricodyn/$', views.CreaScaricoDynView.as_view(), name="creascaricodyn"),
    url(r'^scaricaprodotti/$', views.scaricaProdotti, name="scaricaprodotti"),
    
    url(r'^scarico/(?P<pk>[0-9]+)$', views.ScaricoView.as_view(), name="scarico"),
    url(r'^dettaglioscarico/(?P<pk>[0-9]+)$', views.DettaglioScaricoView.as_view(), name="dettaglioscarico"),
    
    url(r'^vociscarico/$', views.VociScaricoView.as_view(), name="vociscarico"),
    url(r'^creavocescarico/$', views.CreaVoceScaricoView.as_view(), name="creavocescarico"),
    url(r'^vocescarico/(?P<pk>[0-9]+)$', views.VoceScaricoView.as_view(), name="vocescarico"),
    
    url(r'^listafornitori/$', aiace.listaFornitori, name="listafornitori"),
    url(r'^listaclienti/$', aiace.listaClienti, name="listaclienti"),
    url(r'^listaprodotticodice/$', aiace.listaProdottiCodice, name="listaprodotticodice"),
    url(r'^listaprodottidescrizione/$', aiace.listaProdottiDescrizione, name="listaprodottidescrizione"),
    url(r'^validalistaprodotti/$', aiace.validaListaProdotti, name="validalistaprodotti"),
    
]

hobby/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^gestione/', include('gestione.urls', namespace='gestione')),
    url(r'^admin/', admin.site.urls),
]

gestione/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
    descrizione = models.CharField(max_length = 64)
    
    def __str__(self):
        return self.descrizione

class Prodotto(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    codice = models.CharField(max_length = 64)
    descrizione = models.CharField(max_length = 64, blank = True, null = True)
    unitaMisura = models.CharField(max_length = 16)   
    disponibilita = models.IntegerField()
    prezzo = models.FloatField()
    
    def __str__(self):
        return self.codice

class TipoAnagrafica(models.Model):
    tipo = models.CharField(max_length = 16)
    
    def __str__(self):
        return self.tipo
    
class Anagrafica(models.Model):
    nome = models.CharField(max_length = 256)
    piva = models.CharField(max_length = 16, blank = True, null = True)
    indirizzo = models.CharField(max_length = 64, blank = True, null = True)
    citta = models.CharField(max_length = 64, blank = True, null = True)
    cap = models.CharField(max_length = 5, blank = True, null = True)
    provincia = models.CharField(max_length = 2, blank = True, null = True)
    telefono = models.CharField(max_length = 32, blank = True, null = True)
    cellulare = models.CharField(max_length = 32, blank = True, null = True)
    fax = models.CharField(max_length = 32, blank = True, null = True)
    mail = models.CharField(max_length = 64, blank = True, null = True) 
    tipo = models.ForeignKey(TipoAnagrafica, on_delete=models.CASCADE)
    
    def __str__(self):
        return "%s - %s" % (self.nome, self.tipo)
    
class Ricarico(models.Model):
    nome = models.CharField(max_length = 16)
    percentuale = models.FloatField()
    
    def __str__(self):
        return self.nome

class Iva(models.Model):
    nome = models.CharField(max_length = 16)
    percentuale = models.FloatField()
    
    def __str__(self):
        return self.nome
    
class Carico(models.Model):
    data = models.DateField()
    fornitore = models.ForeignKey(Anagrafica, null = True, blank = True)
    
    def __str__(self):
        return '%s %s' % (self.data, self.fornitore)
    
class VoceCarico(models.Model):
    prodotto = models.ForeignKey(Prodotto)
    carico = models.ForeignKey(Carico)
    quantita = models.IntegerField()    
    prezzo = models.FloatField()
    
    def __str__(self):
        return '%s %s' % (self.prodotto, self.carico)
     
class Scarico(models.Model):
    data = models.DateTimeField()
    cliente = models.ForeignKey(Anagrafica, null = True, blank = True)
    
    def __str__(self):
        return '%s %s' % (self.data, self.cliente)
    
class VoceScarico(models.Model):
    prodotto = models.ForeignKey(Prodotto)
    scarico = models.ForeignKey(Scarico)
    quantita = models.IntegerField()    
    prezzo = models.FloatField()
    
    def __str__(self):
        return '%s %s' % (self.prodotto, self.scarico)
    

gestione/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import *
from django.views.generic.base import TemplateView
from django.urls.base import reverse_lazy
from django.contrib import messages
from .baseviews import *
from .aiace import *

"""
Cose da fare:
- form di carico dinamica
- form di scarico dinamica
- lista carichi per anagrafica
- lista scarichi per anagrafica
=> Alla luce di queste ultime due righe, magari servirebbe rivedere il menu: lasciare le voci "grandi" sopra e poi, quando si clicca, sotto compaiono le varie sottovoci
"""

class IndexView(TemplateView):
    template_name = 'gestione/index.html'
    

# PRODOTTO
class MagazzinoView(generic.ListView):
    model = Prodotto
    template_name = 'gestione/prodotto_list.html'    
    context_object_name = 'prodotti'
    
class CreaProdottoView(generic.CreateView):
    model = Prodotto
    template_name = 'gestione/prodotto_create.html'
    fields = '__all__'    
    
    def get_success_url(self):
        messages.info(self.request, "Prodotto %s creato" % self.object)
        return reverse_lazy('gestione:magazzino')
    
class ProdottoView(generic.UpdateView):
    model = Prodotto
    template_name = 'gestione/prodotto_update.html'
    fields = '__all__'
    
    def get_success_url(self):        
        messages.info(self.request, "Prodotto %s modificato" % self.object)        
        return reverse_lazy('gestione:magazzino')
    
# CATEGORIE
class CategorieView(generic.ListView):
    model = Categoria
    template_name = 'gestione/categoria_list.html'    
    context_object_name = 'categorie'
    
class CreaCategoriaView(generic.CreateView):
    model = Categoria
    template_name = 'gestione/categoria_create.html'
    fields = '__all__'
    
    def get_success_url(self):
        messages.info(self.request, "Categoria %s creata" % self.object)
        return reverse_lazy('gestione:categorie')
    
class CategoriaView(generic.UpdateView):
    model = Categoria
    template_name = 'gestione/categoria_update.html'
    fields = '__all__'
    
    def get_success_url(self):
        messages.info(self.request, "Categoria %s modificata" % self.object)
        return reverse_lazy('gestione:categorie')

# TIPO ANAGRAFICA
class TipoAnagraficheView(generic.ListView):
    model = TipoAnagrafica
    template_name = 'gestione/tipoanagrafica_list.html'    
    context_object_name = 'tipoanagrafiche'
    
class CreaTipoAnagraficaView(generic.CreateView):
    model = TipoAnagrafica
    template_name = 'gestione/tipoanagrafica_create.html'
    fields = '__all__'
    
    def get_success_url(self):
        messages.info(self.request, "Tipo Anagrafica %s creato" % self.object)
        return reverse_lazy('gestione:tipoanagrafiche')
    
class TipoAnagraficaView(generic.UpdateView):
    model = TipoAnagrafica
    template_name = 'gestione/tipoanagrafica_update.html'
    fields = '__all__'
    
    def get_success_url(self):
        messages.info(self.request, "Tipo Anagrafica %s modificato" % self.object)
        return reverse_lazy('gestione:tipoanagrafiche')

# Anagrafica
class AnagraficheView(generic.ListView):
    model = Anagrafica
    template_name = 'gestione/anagrafica_list.html'    
    context_object_name = 'anagrafiche'
    
class CreaAnagraficaView(generic.CreateView):
    model = Anagrafica
    template_name = 'gestione/anagrafica_create.html'
    fields = '__all__'
    
    def get_success_url(self):
        messages.info(self.request, "Anagrafica %s creata" % self.object)
        return reverse_lazy('gestione:anagrafiche')
    
class AnagraficaView(generic.UpdateView):
    model = Anagrafica
    template_name = 'gestione/anagrafica_update.html'
    fields = '__all__'
    
    def get_success_url(self):
        messages.info(self.request, "Anagrafica %s modificata" % self.object)
        return reverse_lazy('gestione:anagrafiche')

# RICARICO
class RicarichiView(generic.ListView):
    model = Ricarico
    template_name = 'gestione/ricarico_list.html'    
    context_object_name = 'ricarichi'
    
class CreaRicaricoView(generic.CreateView):
    model = Ricarico
    template_name = 'gestione/ricarico_create.html'
    fields = '__all__'
    
    def get_success_url(self):
        messages.info(self.request, "Ricarico %s creato" % self.object)
        return reverse_lazy('gestione:ricarichi')
    
class RicaricoView(generic.UpdateView):
    model = Ricarico
    template_name = 'gestione/ricarico_update.html'
    fields = '__all__'
    
    def get_success_url(self):
        messages.info(self.request, "Ricarico %s modificato" % self.object)
        return reverse_lazy('gestione:ricarichi')

# IVA
class ListaIVAView(generic.ListView):
    model = Iva
    template_name = 'gestione/iva_list.html'    
    context_object_name = 'iva'
    
class CreaIVAView(generic.CreateView):
    model = Iva
    template_name = 'gestione/iva_create.html'
    fields = '__all__'
    
    def get_success_url(self):
        messages.info(self.request, "IVA %s creata" % self.object)
        return reverse_lazy('gestione:listaiva')
    
class IVAView(generic.UpdateView):
    model = Iva
    template_name = 'gestione/iva_update.html'
    fields = '__all__'
    
    def get_success_url(self):
        messages.info(self.request, "IVA %s modificata" % self.object)
        return reverse_lazy('gestione:listaiva')


# CARICO
class CarichiView(generic.ListView):
    model = Carico
    template_name = 'gestione/carico_list.html'    
    context_object_name = 'carichi'
    
class CreaCaricoView(generic.CreateView):
    model = Carico
    template_name = 'gestione/carico_create.html'
    fields = '__all__'
    
    def get_success_url(self):
        messages.info(self.request, "Carico %s creato" % self.object)
        return reverse_lazy('gestione:carichi')
    
class CreaCaricoDynView(generic.TemplateView):
    """
    Ecco come deve essere.
    Aggiungo una riga.
    Nella riga inserisco il codice
    Il codice autocompleta sia la riga che la descrizione
    Alla fine dell'inserimento devo validare tutte le righe
    Se qualche prodotto non c'è, comunico all'utente: i prodotti tale e tale non ci sono, li creo?
    Se sceglie sì, creo i prodotti
    Se sceglie no, ritorno alla modifica    
    """
    template_name = 'gestione/carico_dyn_create.html'
    
class CaricoView(generic.UpdateView):
    model = Carico
    template_name = 'gestione/carico_update.html'
    fields = '__all__'
    
    def get_success_url(self):
        messages.info(self.request, "Carico %s modificato" % self.object)
        return reverse_lazy('gestione:carichi')
   
class DettaglioCaricoView(DettaglioView):
    model = Carico
    submodel = VoceCarico
    template_name = 'gestione/carico_dettaglio.html'
    fields = '__all__'    

# VOCI DI CARICO
class VociCaricoView(generic.ListView):
    model = VoceCarico
    template_name = 'gestione/vocecarico_list.html'    
    context_object_name = 'vocicarico'
    
class CreaVoceCaricoView(generic.CreateView):
    model = VoceCarico
    template_name = 'gestione/vocecarico_create.html'
    fields = '__all__'
    
    def get_success_url(self):
        messages.info(self.request, "Voce di Carico %s creata" % self.object)
        return reverse_lazy('gestione:vocicarico')
    
class VoceCaricoView(generic.UpdateView):
    model = VoceCarico
    template_name = 'gestione/vocecarico_update.html'
    fields = '__all__'
    
    def get_success_url(self):
        messages.info(self.request, "Voce di Carico %s modificata" % self.object)
        return reverse_lazy('gestione:vocicarico')

class DettaglioScaricoView(DettaglioView):
    model = Scarico
    submodel = VoceScarico
    template_name = 'gestione/scarico_dettaglio.html'
    fields = '__all__'
    
    def getVoci(self, idCarico):
        print("Ma qui non ci entro?")
        return self.submodel.objects.filter(scarico = idCarico)

# SCARICO
class ScarichiView(generic.ListView):
    model = Scarico
    template_name = 'gestione/scarico_list.html'    
    context_object_name = 'scarichi'
    
class CreaScaricoView(generic.CreateView):
    model = Scarico
    template_name = 'gestione/scarico_create.html'
    fields = '__all__'
    
    def get_success_url(self):
        messages.info(self.request, "Scarico %s creato" % self.object)
        return reverse_lazy('gestione:scarichi')
    
class ScaricoView(generic.UpdateView):
    model = Scarico
    template_name = 'gestione/scarico_update.html'
    fields = '__all__'
    
    def get_success_url(self):
        messages.info(self.request, "Scarico %s modificato" % self.object)
        return reverse_lazy('gestione:scarichi')
    
class CreaScaricoDynView(generic.TemplateView):
    """
    Ecco come deve essere.
    Aggiungo una riga.
    Nella riga inserisco il codice
    Il codice autocompleta sia la riga che la descrizione
    Alla fine dell'inserimento devo validare tutte le righe
    Se qualche prodotto non c'è, comunico all'utente: i prodotti tale e tale non ci sono, li creo?
    Se sceglie sì, creo i prodotti
    Se sceglie no, ritorno alla modifica    
    """
    template_name = 'gestione/scarico_dyn_create.html'

# VOCI DI SCARICO
class VociScaricoView(generic.ListView):
    model = VoceScarico
    template_name = 'gestione/vocescarico_list.html'    
    context_object_name = 'vociscarico'
    
class CreaVoceScaricoView(generic.CreateView):
    model = VoceScarico
    template_name = 'gestione/vocescarico_create.html'
    fields = '__all__'
    
    def get_success_url(self):
        messages.info(self.request, "Voce di Scarico %s creata" % self.object)
        return reverse_lazy('gestione:vociscarico')
    
class VoceScaricoView(generic.UpdateView):
    model = VoceScarico
    template_name = 'gestione/vocescarico_update.html'
    fields = '__all__'
    
    def get_success_url(self):

gestione/templates/gestione/carico_dettaglio.html
{% extends 'gestione/base.html' %}
{% block body_block %}

<h1>Dettagli carico</h1>
<h2>Data: {{ Nome.data }}</h2>
<h2>Fornitore: <a href="{% url 'gestione:anagrafica' Nome.fornitore.id %}">{{ Nome.fornitore }}</a></h2>

<div>
	<input type="button" onclick="location.href='{% url 'gestione:carico' Nome.id %}';" value="Modifica questo carico" />
</div>

<br>
{% if Voci %}
<table class="lista">
	<tr>
		<th>Prodotto</th>
		<th>Unit&agrave; di misura</th>
		<th>Quantita</th>
		<th>Prezzo di acquisto</th>
	</tr>
	{% for v in Voci %}
	<tr>
		<td><a title="Dettagli prodotto"
			href="{% url 'gestione:prodotto' v.prodotto.id %}">{{ v.prodotto }}</a></td>
		<td>{{ v.unitaMisura }}</td>
		<td>{{ v.quantita }}</td>
		<td>{{ v.prezzo }}</td>
	</tr>
	{% endfor %}
</table>
{% else %}
<p>Nessuna Voce.</p>
{% endif %}

{% endblock %}

gestione/templates/gestione/iva_create.html
{% extends 'gestione/base.html' %}


{% block body_block %}
<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Crea IVA"></input>
</form>

{% endblock %}

gestione/templates/gestione/scarico_dyn_create.html
{% extends 'gestione/base.html' %}


{% block body_block %}

<div class="contenitoreform">
	<form id="creazionescarico" action="{% url 'gestione:scaricaprodotti' %}" method="post">
		{% csrf_token %}
		<p>
			<label for="id_data">Data:</label>
			<input id="id_data" name="data" type="text" required />
		</p>
		<p>
			<label for="id_cliente">Cliente:</label>
			<input id="id_cliente" name="cliente" type="text" required "/>		
		</p>
		
	<br>
	<div id="contenitore_prodotti">
	    <table class="lista" id="tabella_prodotti">
	        <tr>
	            <th>Codice</th>
	            <th>Descrizione</th>
	            <th>Quantit&agrave;</th>
	            <th>Prezzo unitario</th>
	            <th>Totale</th>
	            <th>Cancella</th>
	        </tr>
	    </table>
	</div>
	
	<button id="aggiungi_prodotto">Aggiungi Prodotto</button>
	<br>
	<button id="crea_scarico">Crea Scarico</button>
	<input type="submit" value="Crea Scarico" id="submitgenerale"></input>	
	</form>
</div>

<div id="msg_dialog"><div id="contentHolder"></div></div>

<script>

$("#submitgenerale").hide();

function bindAutocompleteSelect(id, funzione) {
	$("#" + id).on("autocompleteselect", funzione)
}

// Autocomplete del fornitore
$("#id_cliente").autocomplete({
	source: function(request, response) {
// 		console.log("Ricerca: " + request.term);
		data ={};
		data['Cliente'] = request.term;
		$.ajax({
			dataType: "json",
			type: 'Get',
			url: '{% url 'gestione:listaclienti' %}',
			data: data,
			success: function(data) {
                                response($.map(data, function(item){
                            		return {
                            			value: item.nome
                            	}}));
			}
		})
	},
	change: function(event, ui) {
		if (!ui.item) {
			$("#id_fornitore").val("");
		}
	}
});

	
$('.ui-autocomplete-input').css('width','300px')


var prodottoHelper = {}
var codiceHelper = {}


$("#id_data").datepicker({ dateFormat: "dd/mm/yy"}).datepicker("setDate", new Date());


var idElemento = 0;

function creaInput(padre, id, classe, r) {
	stringa = '<td><input id="' + id + '" name="' + id + '" type="text" class="' + classe + '"';
	if (r == true) {
		stringa += " required";
	}
	stringa += ' /></td>';
	padre.append(stringa);
}

$("#aggiungi_prodotto").click(function() {
	var oggetto = $('<tr/>');
	
	var questoIdElemento = idElemento;
	
	var elementoCodice = "id_codice" + questoIdElemento;
	var elementoProdotto = "id_prodotto" + questoIdElemento;
	var elementoQuantita = "id_quantita" + questoIdElemento;
	var elementoPrezzoUnitario = "id_prezzo" + questoIdElemento;
	var elementoPrezzoTotale = "id_totale" + questoIdElemento;
	
	oggetto.addClass('prodottodinamico');
	oggetto.attr('id', 'riga' + questoIdElemento);

	creaInput(oggetto, elementoCodice, 'inputCodice', true);
	creaInput(oggetto, elementoProdotto, 'inputProdotto', false);	
	creaInput(oggetto, elementoQuantita, 'inputQuantita', true);
	creaInput(oggetto, elementoPrezzoUnitario, 'inputPrezzo', true);
	
	var stringa = '<td>';
	stringa = stringa + '<a data-id="' + questoIdElemento + '" class="bottonecalcola" href="#">Calcola</a>';
	stringa = stringa + '<input id="' + elementoPrezzoTotale + '" name="' + elementoPrezzoTotale + '" type="text" class="inputTotale" width="5"/>';
	stringa = stringa + '</td>';
	
	oggetto.append(stringa);
// 	creaInput(oggetto, elementoPrezzoTotale);
	
	oggetto.append('<td><a class="cancellaprodotto" href="#">Cancella</a></td>');

	$("#tabella_prodotti").append(oggetto);
	
	// Ricerca per codice	
	$("#" + elementoCodice).autocomplete({
		source: function(request, response) {			
			
			$.ajax({
				dataType: "json",
				type: 'Get',
				url: '{% url 'gestione:listaprodotticodice' %}',
				data: {
                                    'Codice': request.term
				},
				success: function(data) {
                                    response($.map(data, function(item) {                                        
                                        return {
                                            label: item.codice,
                                            id: item.id,
                                            descrizione: item.descrizione,
                                            elemento: questoIdElemento
                                        }
                                    }));
				}
			})
		}		
	});
	
	$("#" + elementoCodice).on("autocompleteselect", function(event, ui) {
            $("#" + elementoProdotto).val(ui.item.descrizione);
	});
	
	
	// Ricerca per descrizione	
	$("#" + elementoProdotto).autocomplete({
		source: function(request, response) {			
			
			$.ajax({
				dataType: "json",
				type: 'Get',
				url: '{% url 'gestione:listaprodottidescrizione' %}',
				data: {
                                    'Descrizione': request.term
				},
				success: function(data) {
                                    response($.map(data, function(item) {                                        
                                        return {
                                            label: item.descrizione,
                                            id: item.id,
                                            codice: item.codice,
                                            elemento: questoIdElemento
                                        }
                                    }));
				}
			})
		}
	});
	
	$("#" + elementoProdotto).on("autocompleteselect", function(event, ui) {
            $("#" + elementoCodice).val(ui.item.codice);
	});
	
	idElemento ++;
});


$('#tabella_prodotti').on('click', 'a.cancellaprodotto', function(events) {
    events.preventDefault();
    $(this).parent().parent().remove();    
});


$('#tabella_prodotti').on('click', 'a.bottonecalcola', function(events) {
    events.preventDefault();
    var id = $(this).data('id');
    console.log("Premuto bottone: " + id);
    
    var quantita = parseFloat($("#id_quantita" + id).val());
    if (isNaN(quantita)) return;    
    
    var prezzo = parseFloat($("#id_prezzo" + id).val());
    if (isNaN(prezzo)) return;
    
    $("#id_totale" + id).val(prezzo * quantita);
    
});


function creaListaProdotti() {
	var validandi = [];
	
	$(".prodottodinamico").each(function(index, Element) {
		var codice = $(this).find(".inputCodice").val();
		var desc = $(this).find(".inputProdotto").val();
		var quantita = $(this).find(".inputQuantita").val();
		var prezzo = $(this).find(".inputPrezzo").val();
		
		validandi.push({ "codice" : codice, "desc": desc, "quantita": quantita, "prezzo": prezzo});
	});
	
	return validandi;
}

function caricaProdottiDef() {
	
	console.log("caricaProdottiDef");
	
	$("#creazionescarico").submit();
	
}


// Submit del form principale
$("#crea_carico").click(function() {
	
	var prodotti = $(".prodottodinamico").length;
	if (prodotti == 0) {
		$("#contentHolder").html("Nessun prodotto selezionato");
		var dialog = $('#msg_dialog').dialog();
		dialog.dialog({
			modal: true,
			autoOpen: true,
			title: "Nessun prodotto",
			buttons: [
				{
					text: 'Ok',
					click: function() {
						$('#msg_dialog').dialog('close');
					}
				}
			]
		});
		return;	
	}
	
	var validandi = creaListaProdotti();
	
	$.ajax({
		dataType: "json",
		type: 'POST',
		url: '{% url 'gestione:validalistaprodotti' %}',
		data: {
			"csrfmiddlewaretoken": $("input[name='csrfmiddlewaretoken']").val(),	
			"lista": JSON.stringify(validandi),
		},
		success: function(response) {
			if (response.length > 0) {
				var trHTML = "<h3>I seguenti prodotti non esistono.</h3>";
				trHTML += "<table><tr><th>Codice</th><th>Descrizione</th></tr>"
				$.each(response, function(i, e) {
					trHTML += "<tr><td>" + e.codice + "</td><td>" + e.desc + "</td></tr>";
				});
				trHTML += "</table>";
				
				$("#contentHolder").html(trHTML);
				
				var dialog = $('#msg_dialog').dialog();
				dialog.dialog({
					modal: true,
					autoOpen: true,
					title: "Verifica prodotti",
					buttons: [
						{
							text: 'Ok',
							click: function() {
								$('#msg_dialog').dialog('close');
								
							}
						}
					]
				});
				
			} else {
				caricaProdottiDef();
			}
			
		}
	})
	
	
});

</script>

{% endblock %}